data_source retail:
  type: bigquery
  connection:
    account_info_json_path: /usr/local/airflow/include/gcp/service_account.json
    auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
    project_id: 'airflow-tutorial-411419'
    dataset: retail
soda_cloud:
  host: cloud.soda.io
  api_key_id: 9ab7811d-0899-41fe-964a-abadd5a46981
  api_key_secret: wOj4XFo25CylGmgJmin0YCxwgnGjV6G76eAPpNO5i_Ao5uAvt2E8Ow